;x,y,z,imageid,size,transcol
;red square
Data.l     -128,-160,0,2,2,0
Data.l     -64,-160,0,2,2,0
Data.l     0,-160,0,2,2,0
Data.l     64,-160,0,2,2,0
Data.l     128,-160,0,2,2,0
Data.l     -128,-96,0,2,2,0
Data.l     128,-96,0,2,2,0
Data.l     -128,-32,0,2,2,0
Data.l     0,-32,0,1,4,0
Data.l     128,-32,0,2,2,0
Data.l     -128,32,0,2,2,0
Data.l     128,32,0,2,2,0
Data.l     -128,96,0,2,2,0
Data.l     -64,96,0,2,2,0
Data.l     0,96,0,2,2,0
Data.l     64,96,0,2,2,0
Data.l     128,96,0,2,2,0

; IDE Options = PureBasic 5.73 LTS (Windows - x86)
; CursorPosition = 1
; EnableXP
; DPIAware
; DisableDebugger
; HideErrorLog