;x,y,z,imageid,size,transcol
;grey P
Data.l     -32,-128,64,3,2,0
Data.l     0,-128,64,3,2,0
Data.l     32,-128,64,3,2,0
Data.l     -32,-96,64,3,2,0
Data.l     32,-96,64,3,2,0
Data.l     -32,-64,64,3,2,0
Data.l     0,-64,64,3,2,0
Data.l     32,-64,64,3,2,0
Data.l     -32,-32,64,3,2,0
Data.l     -32,0,64,3,2,0
Data.l     -32,32,64,3,2,0
Data.l     -32,64,64,3,2,0

; IDE Options = PureBasic 5.73 LTS (Windows - x86)
; CursorPosition = 1
; EnableXP
; DPIAware
; DisableDebugger
; HideErrorLog